apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: ls-workspace
spec:
  params:
    - name: path
      type: string
      default: "./"
      description: >
        Relative path.
  workspaces:
    - name: folder
  steps:
    - name: list
      image: ubuntu
      workingDir: $(workspaces.folder.path)
      script: |
        pwd
        ls $(params.path)